import React from "react";
import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

function Layout({ title, children }) {
  return (
    <div>
      <Head>
        <title>{title ? title + "- Amazon" : "Amazon"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen justify-between">
        <Header />
        <div className="container m-auto mt-4 px-4">{children}</div>;
        <Footer />
      </div>
    </div>
  );
}

export default Layout;
